project:
  type: website
  output-dir: docs

website:
  site-url: https://quantecol.com.au
  title: "Quantecol"
  image: "img/Logo-Quantecol-RGB-FA-2-1000.png"
  favicon: "img/Icon-Quantecol-RGB-FA-1-500.png"
  twitter-card: true
  open-graph: true
  navbar:
    title: false
    logo: "img/Logo-Quantecol-RGB-FA-2-1000.png"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Services"
        href: services.qmd
      - text: "Portfolio"
        href: portfolio.qmd
      - text: "Blog"
        href: blog.qmd
        menu: 
          - text: "A unified approach to ecological modeling in Stan"
            href: blog/hmm-in-stan.qmd
      - text: "About"
        menu:
          - text: "Our Vision"
            href: about/vision.qmd
          - text: "People"
            href: about/people/matthijs.qmd
          - text: "Contact Us"
            href: about/contact.qmd
    right:
      - icon: twitter
        href: https://twitter.com/realQuantecol
      
  page-footer: 
    center: "Quantecol | 53 Bentinck Street, Ballina NSW, Australia | ABN: 90 710 874 314"

format:
  html:
    theme: 
      light: [flatly, custom.scss]
    css: styles.css
    toc: false
  
freeze: true



